#PBS -N xi
#PBS -l nodes=1:ppn=60
#PBS -l walltime=72:00:00
#PBS -q normal
#PBS -o /home/yunzheng/mock/clustering/code/xis_direct/output/xi19.0.o
#PBS -e /home/yunzheng/mock/clustering/code/xis_direct/output/xi19.0.e

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!

__conda_setup="$('/home/yunzheng/anaconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/yunzheng/anaconda/etc/profile.d/conda.sh" ]; then
        . "/home/yunzheng/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/yunzheng/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup


#__conda_setup="$('/home/yunzheng/anaconda/envs/py37/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else       
#    if [ -f "/home/yunzheng/anaconda/envs/py37/etc/profile.d/conda.sh" ]; then
#        . "/home/yunzheng/anaconda/envs/py37/etc/profile.d/conda.sh"
#    else     
#        export PATH="/home/yunzheng/anaconda/envs/py37/bin:$PATH"
#    fi
#fi 
#unset __conda_setup
# <<< conda initialize <<<
conda activate py37
module load compiler/gcc-10.2.0

#job start
cd /home/yunzheng/mock/clustering/code/xis_direct
python -u /home/yunzheng/mock/clustering/code/xis_direct/xismu5.py

